### ISSUE TITLE
[1.16.5-1.0.5] Crash on entering overworld from nether

### ISSUE THREAD

**Issue by LuciusV** [HexoMod/Chest-Locator#1]
Game crashed once when I travel back to overworld with providing crash log indicating some chest locator code

It only happened once, did not crashed when I reloaded world and moved through the same portal.
[crash-2021-02-15_09.18.25-client.txt](https://github.com/HexoMod/Chest-Locator/files/5979036/crash-2021-02-15_09.18.25-client.txt)

**Comment by hexosse** [comment]
This should be solved in version 1.0.6
