### ISSUE TITLE
1.16.5 Issues with IceAndFire ghost chests/ any chests that extend ChestTileEntity

### ISSUE THREAD

**Issue by TheBv** [HexoMod/Chest-Locator#2]
Basically the issue is that the mod at some point checks if the current object is of type ChestTileEntity and then proceeds to cast the object to a TrappedChestTileEntity.
This is problematic since in the case that a TileEntity extends the ChestTileEntity it can not be cast to an instance of a TrappedChestTileEntity. 
This is the case with the [TileEntityGhostChest](https://github.com/Alex-the-666/Ice_and_Fire/blob/bdd40cfb447e1578c57b5272b8ff0c0707c1c8c4/src/main/java/com/github/alexthe666/iceandfire/entity/tile/TileEntityGhostChest.java) from the Ice and Fire mod. (related [issue](https://github.com/Alex-the-666/Ice_and_Fire/issues/3627) with logfile)

**Comment by hexosse** [comment]
This should be solved in version 1.0.6
